#!/usr/bin/python

import sys, os, os.path

f = open('body/expMueller.tex', 'w')

f.write( '''
\\begin{figure}[!htbp]
    \centering
    \subfigure[y = 15mm]{
        \label{fig:averageVelocity09_15}
        \includegraphics[width=0.45\\textwidth]{figs/timeAveragedVelocity09_1}
        }
    \hspace{0.03\\textwidth}
    \subfigure[y = 25mm]{
        \label{fig:averageVelocity09_25}
        \includegraphics[width=0.45\\textwidth]{figs/timeAveragedVelocity09_2}
        }
    \\vspace{0.03\\textwidth}
    \subfigure[y = 35mm]{
        \label{fig:averageVelocity09_35}
        \includegraphics[width=0.45\\textwidth]{figs/timeAveragedVelocity09_3}
        }
        \caption{Time-averaged velocity in different sections from:
                 a) Mueller et al.'s experiment, b) previous simulation,
                 c) present simulation. In this case, $U = 0.9$~m/s}
    \label{fig:MuellerAverageVelocity09}
\end{figure}

\\begin{figure}[!htbp]
    \centering
    \subfigure[y = 16.4mm]{
        \label{fig:averageVoidage09_164}
        \includegraphics[width=0.45\\textwidth]{figs/fluidVolumeFraction09_1}
        }
    \hspace{0.03\\textwidth}
    \subfigure[y = 31.2mm]{
        \label{fig:averageVoidage09_312}
        \includegraphics[width=0.45\\textwidth]{figs/fluidVolumeFraction09_2}
        }
        \caption{Time-averaged fluid volume fraction in different sections from:
                 a) Mueller et al.'s experiment, b) previous simulation,
                 c) present simulation. In this case, $U = 0.9$~m/s}
    \label{fig:MuellerVoidage09}
\end{figure}

\\begin{figure}[!htbp]
    \centering
    \label{fig:averageVelocity06_20}
    \includegraphics[width=0.45\\textwidth]{figs/timeAveragedVelocity06_1}
    \caption{Time-averaged velocity in different sections from:
             a) Mueller et al.'s experiment, b) previous simulation,
             c) present simulation. In this case, $U = 0.6$~m/s}
    \label{fig:MuellerAverageVelocity06}
\end{figure}

\\begin{figure}[!htbp]
    \centering
    \subfigure[y = 16.4mm]{
        \label{fig:averageVoidage06_164}
        \includegraphics[width=0.45\\textwidth]{figs/fluidVolumeFraction06_1}
        }
    \hspace{0.03\\textwidth}
    \subfigure[y = 31.2mm]{
        \label{fig:averageVoidage06_312}
        \includegraphics[width=0.45\\textwidth]{figs/fluidVolumeFraction06_2}
        }
        \caption{Time-averaged fluid volume fraction in different sections from:
                 a) Mueller et al.'s experiment, b) previous simulation,
                 c) present simulation. In this case, $U = 0.6$~m/s}
    \label{fig:MuellerVoidage06}
\end{figure}
(Note: This section is generated by Python.)
''' )

f.close();

cmd='cat body/expMueller.tex >> lammps-paper.tex'
os.system(cmd)
