# type "make" command in Unix to create mets.pdf file 
all:
	pdflatex lammps-paper
	pdflatex lammps-paper

clean:
	(rm -rf *.ps *.log *.dvi *.aux *.*% *.lof *.lop *.lot *.toc *.idx *.ilg *.ind *.bbl *blg)
