#!/usr/bin/python

import sys, os, os.path

f = open('body/singleParticle.tex', 'w')

f.write( '''
\\begin{figure}[!htbp]
  \centering
    \includegraphics[width=0.45\\textwidth]{figs/singleParticle}
    \caption{The velocity of a particle from: 
             a) Xiao et al.'s CICP paper, b) previous simulation
             c) present simulation.}
    \label{fig:singleParticle}
\end{figure}
(Note: This section is generated by Python.)
''' )

f.close();

cmd='cat body/singleParticle.tex >> lammps-paper.tex'
os.system(cmd)
