#!/usr/bin/python

import sys, os, os.path

f = open('body/multiParticle.tex', 'w')

f.write( '''
\\begin{figure}[!htbp]
    \centering
    \subfigure[Particle Velocity]{
        \label{fig:multiParticleVelocityRho}
        \includegraphics[width=0.45\\textwidth]{figs/multiParticlesVelocityRho}
        }
    \hspace{0.03\\textwidth}
    \subfigure[Particle Position]{
        \label{fig:multiParticlePositionRho}
        \includegraphics[width=0.45\\textwidth]{figs/multiParticlesPositionRho}
        }
        \caption{The velocity and position of particles after collision. The density of 
                 different particles is different. 
                 Panel a) shows the particle velocity at different times while
                 Panel b) shows the particle trajectory.}
    \label{fig:multiParticleCollisionRho}
\end{figure}

\\begin{figure}[!htbp]
    \centering
    \subfigure[Particle Velocity]{
        \label{fig:multiParticleVelocityDia}
        \includegraphics[width=0.45\\textwidth]{figs/multiParticlesVelocityDia}
        }
    \hspace{0.03\\textwidth}
    \subfigure[Particle Position]{
        \label{fig:multiParticlePositionDia}
        \includegraphics[width=0.45\\textwidth]{figs/multiParticlesPositionDia}
        }
        \caption{The velocity and position of particles after collision. The diameter of
                 different particles is different.
                 Panel a) shows the particle velocity at different times while
                 Panel b) shows the particle trajectory.}
    \label{fig:multiParticleCollisionDia}
\end{figure}
(Note: This section is generated by Python.)
''' )

f.close();

cmd='cat body/multiParticle.tex >> lammps-paper.tex'
os.system(cmd)
