#!/usr/bin/python

import sys, os, os.path

f = open('body/pressureDrop.tex', 'w')

f.write( '''
\\begin{figure}[!htbp]
  \centering
    \includegraphics[width=0.8\\textwidth]{figs/pressureDrop}
    \caption{The pressure drop of different points in time domain from:
             a) Xiao et al.'s CICP paper, b) present simulation.
             Also, the minimum fluidized velocity is shown.}
    \label{fig:pressureDrop}
\end{figure}
(Note: This section is generated by Python.)
''' )

f.close();

cmd='cat body/pressureDrop.tex >> lammps-paper.tex'
os.system(cmd)
